name: 'PrepareRelease'
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (optional)
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: "Run craft prepare"
    steps:
      - uses: actions/checkout@v2

      - id: set-env
        run: |
          echo 'RELEASE_VERSION=${{ github.event.inputs.version }}' >> $GITHUB_ENV;
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' >> $GITHUB_ENV;
      - id: set-git-user
        run: |
          git config user.name omnivector-qa
          git config user.email admin@omnivector.solutions
      - uses: getsentry/craft@master
        name: "Craft Prepare"
        with:
          action: prepare
          version: ${{ env.RELEASE_VERSION }}
        env:
          GIT_COMMITTER_NAME: omnivector-qa
          GIT_AUTHOR_NAME: omnivector-qa
          EMAIL: admin@omnivector.solutions

  build:
    runs-on: ubuntu-latest
    name: "Build artifacts for the release"
    needs: [prepare]
    steps:
      - id: set-version
        run: |
          echo 'RELEASE_VERSION=${{ github.event.inputs.version }}' >> $GITHUB_ENV;
          echo 'RELEASE_PREFIX=slurm-bundles-${{ github.event.inputs.version }}' >> $GITHUB_ENV;
      - uses: actions/checkout@v2
        with:
          ref: release/${{ env.RELEASE_VERSION }}

      - id: set-git-user
        run: |
          git config user.name omnivector-qa
          git config user.email admin@omnivector.solutions
      - name: "tar it up"
        run: |
          git ls-tree --name-only -z HEAD \
            | tar --transform 's,^,${{ env.RELEASE_PREFIX }}/,' --null -T- -cvz -f ${{ env.RELEASE_PREFIX }}.tar.gz
      - name: "Parse and store git_sha, release_version"
        if: ${{ success() }}
        id: vars
        shell: bash
        run: |
          echo "::set-output name=release_version::$(echo $(git branch | grep '*' | awk '{print $2}') | sed 's/[a-z-]*\///g')"
          echo "::set-output name=tarball::$(echo ${{ env.RELEASE_PREFIX }}.tar.gz)"
          echo "::set-output name=git_sha::$(git rev-parse HEAD)"
      - name: Upload Artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.git_sha }}
          path: |
            ${{ steps.vars.outputs.tarball }}
      - uses: Sibz/github-status-action@v1
        if: ${{ success() }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'ReleaseAction'
          description: 'Passed'
          state: 'success'
          sha: ${{ steps.vars.outputs.git_sha }}
