name: 'PublishRelease'

on:
  workflow_dispatch:
    inputs:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: "Upload the artifact"
    steps:
      - uses: actions/checkout@v2

      - name: "Parse and store the release_version"
        id: vars
        shell: bash
        run: |
          echo "::set-output name=release_version::$(echo $(git branch | grep '*' | awk '{print$2}') | sed 's/[a-z-]*\///g')"
      - id: set-env
        if: ${{ success() }}
        run: |
          echo 'RELEASE_VERSION=${{ steps.vars.outputs.release_version }}' >> $GITHUB_ENV;
      - id: set-git-user
        run: |
          git config user.name omnivector-qa
          git config user.email admin@omnivector.solutions
      - uses: getsentry/craft@master
        if: ${{ success() }}
        name: "Craft Publish"
        with:
          action: publish
          version: ${{ env.RELEASE_VERSION }}
          keep_branch: "--keep-branch"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CRAFT_LOG_LEVEL: debug

      - id: next-dev-version
        if: ${{ success() }}
        run: |
          git fetch --all
          git checkout master
          ./scripts/bump-version.sh '' "${{ env.RELEASE_VERSION }}+dev"
          git diff --quiet || git commit -anm 'meta: Bump new development version' && git pull --rebase && git push
